### ISSUE TITLE
docker-compose up does not work

### ISSUE THREAD

**Issue by Maddimax** [greenpress/greenpress#82]
`git clone https://github.com/greenpress/greenpress.git`

Going just by the documentation:

```
docker-compose up

ERROR: The Compose file './docker-compose.yml' is invalid because:
services.greenpress.ports is invalid: Port ranges don't match in length
```

```
PORT=7000 docker-compose up

WARNING: The MONGODB_VOLUME variable is not set. Defaulting to a blank string.
WARNING: The GREENPRESS_IMAGE variable is not set. Defaulting to a blank string.
WARNING: The TENANT variable is not set. Defaulting to a blank string.
WARNING: The JWT_SECRET variable is not set. Defaulting to a blank string.
WARNING: The THEME variable is not set. Defaulting to a blank string.
WARNING: The REFRESH_TOKEN_SECRET variable is not set. Defaulting to a blank string.
WARNING: The SECRETS_SERVICE_SECRET variable is not set. Defaulting to a blank string.
WARNING: The ASSETS_SECRETS_TOKEN variable is not set. Defaulting to a blank string.
WARNING: The INTERNAL_SECRET variable is not set. Defaulting to a blank string.
WARNING: The MAX_MEMORY_USAGE variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 542, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent, cli=cli)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 354, in ensure_image_exists
    self.image()
  File "/usr/lib/python3/dist-packages/compose/service.py", line 380, in image
    return self.client.inspect_image(self.image_name)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 16, in wrapped
    raise errors.NullResource(
docker.errors.NullResource: Resource ID was not provided
```

**Comment by davidmeirlevy** [comment]
you'll need to copy the `.env.example` and create a `.env` file.
but mostly, it will currently use greenpress 1.2.3 and it will pull it from dockerhub, mainly because our latest version of greenpress (2.0.0) wasn't pushed to dockerhub yet (the app is the same, we just changed it from polyrepo to monorepo).

**Comment by Maddimax** [comment]
Then this should be mentioned in the main README.md I think.

**Comment by davidmeirlevy** [comment]
yeah, I'll add it now (also we just merged the polyrepos to this monorepo 3 days ago..).

**Comment by davidmeirlevy** [comment]
@Maddimax done. the readme is updated. thanks!
