### ISSUE TITLE
[BUG] greenpress start dev command

### ISSUE THREAD

**Issue by Man-RP** [greenpress/greenpress#91]
node version 14.15.4
npm version 6.14.10
greenpress version 0.5
getting the following error after running greenpress start dev:

```
The MAX_MEMORY_USAGE variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "docker\api\client.py", line 214, in _retrieve_server_version
  File "docker\api\daemon.py", line 181, in version
  File "docker\utils\decorators.py", line 46, in inner
  File "docker\api\client.py", line 237, in _get
  File "requests\sessions.py", line 543, in get
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1255, in request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "http\client.py", line 1010, in _send_output
  File "http\client.py", line 950, in send
  File "docker\transport\npipeconn.py", line 32, in connect
  File "docker\transport\npipesocket.py", line 23, in wrapped
  File "docker\transport\npipesocket.py", line 72, in connect
  File "docker\transport\npipesocket.py", line 52, in connect
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 81, in main
  File "compose\cli\main.py", line 199, in perform_command
  File "compose\cli\command.py", line 60, in project_from_options
  File "compose\cli\command.py", line 152, in get_project
  File "compose\cli\docker_client.py", line 41, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "docker\api\client.py", line 197, in __init__
  File "docker\api\client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
[2532] Failed to execute script docker-compose
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! greenpress-docker-scripts@ local:compose-up: `docker-compose -f docker-compose.local.yml -p greenpress up --build -d`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the greenpress-docker-scripts@ local:compose-up script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

```

**Comment by zvikfir** [comment]
@davidmeirlevy  I'm also having an issue with starting the application.

I followed the instructions given in the [docs](https://docs.greenpress.info/guide/getting-started.html#installation), tried to run `greenpress start dev`, and received the following message:

```
Initializing Greenpress..

Doing our magic, might take a few minutes. Please wait.

process exited
An error occurred during server startup
```

**Comment by zvikfir** [comment]
I managed to solve the problem. I ran `npm install`, then `npm run dev`. I got the following error:

```
... /greenpress-app/apps/greenpress/node_modules/.bin/gp-cli-service-pm2-dev: line 1: pm2-runtime: command not found
lerna ERR! npm run dev exited 127 in '@greenpress/greenpress'
lerna ERR! npm run dev exited 127 in '@greenpress/greenpress'
```

I installed `pm2` using `npm i -g pm2` as root, and then I could run both `npm run dev` and `greenpress start dev`.

**Comment by davidmeirlevy** [comment]
Hi @zvikfir !

I just upgraded the CLI two days ago, so it's great to see that some of the issues were fixed and there are also things we need to add :)
would you like to participate in this fix?

From what I see, this issue is probably related to the installation process and not to the "start" process.
So the fixes are:

1. on the CLI (at `tools/cli`) at the `create` command, we should run `npm install` after the `git clone` of the project.
That will make sure the user has all the packages.
2. we should then execute `npm i -g pm2` for the user, in case `which pm2` returns an error.

What do you say?

**Comment by zvikfir** [comment]
No problem. I'll take it.

I will post an update here in case I run into problems.

**Comment by zvikfir** [comment]
@davidmeirlevy `pm2` is usually installed globally. However, there are permissions issues when trying to install a module globally. How should I proceed? Should I install the module locally?

To test whether my code works, I am running the cli using `node tools/cli/cli.js`. Maybe the permissions issue occurs only when running this way, and not when running via the `greenpress` npm package?

**Comment by davidmeirlevy** [comment]
the best way to debug the cli, go to `tools/cli/cli.js` and run `npm link`.
after that, when you run the CLI commands (like `greenpress create my-app`), no matter where - it will use the CLI from your local project.

**Comment by zvikfir** [comment]
[This](https://github.com/zvikfir/greenpress/commit/79c356beedf8804147f72c53e726a018132cc740) is what I have done so far.

It runs `npm install` as intended after cloning, and then checks if `pm2` is installed using `which`. However, it only performs local installation if it is missing. As I have stated, I am running into permission issues when trying to install globally.

I'd be happy to assist with additional changes. I just don't know how to proceed.

**Comment by davidmeirlevy** [comment]
@zvikfir can you create a PR so I could review it?

Thanks.
